[package]
name = "filewatcher"
version = "0.1.0"
authors = ["Scarjit <scarjit@aol.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = "0.10.1"
rodio = "0.11.0"
notify = "5.0.0-pre.2"
lazy_static = "1.4.0"